services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    restart: unless-stopped
    command: npx ts-node src/main.ts
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    restart: unless-stopped
    command: npx ng serve --host 0.0.0.0 --port 4200
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
