version: "3"

services:
  backend:
    build:
      context: .                # 👈 root includes frontend/, backend/, cert/
      dockerfile: backend/Dockerfile
    ports:
      - "443:443"
    restart: unless-stopped
