services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "443:443"
    volumes:
      - ./cert:/app/cert
      - ./backend:/app/backend 
      - ./frontend:/app/frontend
      - ./db:/app/db
    restart: unless-stopped
