services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: transcendance_backend
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./db:/app/db
    expose:
      - "3000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: transcendance_frontend
    ports:
      - "443:443"
    volumes:
      - ./cert:/etc/nginx/cert
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge