{
 "title": "Transcendance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 0 },
   "options": {
    "content": "\n<h1 style=\"font-size:30px; color:white;\">TRANSCENDANCE MONITORING DASHBOARD</h1>\n"
   }
  },
  { "title": "SYSTEM MONITORING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "System health",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU usage (avg %)"
    },
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "Memory usage (%)"
    },
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "Disk usage (%)"
    }
   ]
  },
  {
   "title": "Backend up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Run time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total[5m]))",
     "legendFormat": "Disk read"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total[5m]))",
     "legendFormat": "Disk write"
    }
   ]
  },
  {
   "title": "Disk I per device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(device)(rate(node_disk_reads_completed_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk O per device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum by(device)(rate(node_disk_writes_completed_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic(bytes/second)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]) + rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network iowait (%/second)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))",
     "legendFormat": "Network iowait (%/second)"
    }
   ]
  },
  { "title": "APP PERFORMANCE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "GET POST rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\"}[5m]))",
     "legendFormat": "Average POST counts"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"GET\"}[5m]))",
     "legendFormat": "Average GET counts"
    }
   ]
  },
  {
   "title": "Success request rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 36 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"2..\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests overview",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 22, "x": 0, "y": 44 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 58 },
   "targets": [
    { "expr": "rate(app_users_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 16, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recorded match trend (DB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 67 },
   "targets": [
    { "expr": "rate(app_matches_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total matches (DB)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 16, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_matches_total", "legendFormat": "__auto" }
   ]
  }
 ]
}