global:
  scrape_interval: 20s

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['transcendance_backend:3000']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
